version: "3"
services:
  node-app:
    # container_name: express-demo-container-docker
    image: 2880932/docker-nodeapi
    # ports:
    #   - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - mongo
      # - postgres
      - redis
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 2
        delay: 10s
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   depends_on:
  #     - mongo
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  redis:
    image: redis
  nginx:
    image: nginx:stable-alpine
    ports:
    - "83:82"
    depends_on:
      - node-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  # postgres:
  #   image: postgres
  #   restart: always
  #   volumes:
  #     - postgres-db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: example


volumes:
  mongo-db: